# Exercise metadata for speaker-note generation.
from __future__ import annotations

EXERCISE_META: dict[tuple[int, int], dict] = {
    (2, 1): {"title": "Codebase Understanding", "time": "20 min", "type": "cursor",
             "core": "exercise-1/01-open-agent-first-prompt.md",
             "objective": "Use the Cursor Agent to orient yourself in an unfamiliar repository."},
    (2, 2): {"title": "Explaining a Specific File or Symbol", "time": "13 min", "type": "cursor",
             "core": "exercise-2/02-explain-a-specific-file.md",
             "objective": "Get targeted explanations of one file or symbol without reading the whole repo."},
    (2, 3): {"title": "Making a Safe, Reviewable Change", "time": "13 min", "type": "cursor",
             "core": "exercise-3/03-make-a-safe-change.md",
             "objective": "Let the Agent propose a small change and review the diff before accepting."},
    (2, 4): {"title": "Plan Mode", "time": "13 min", "type": "cursor",
             "core": "exercise-4/04-use-plan-mode.md",
             "objective": "Use Plan Mode to design a change before the Agent edits files."},
    (2, 5): {"title": "Comparing Two Models", "time": "13 min", "type": "cursor",
             "core": "exercise-5/05-compare-two-models.md",
             "objective": "Run the same prompt on two models and compare quality, speed, and cost."},
    (2, 6): {"title": "Precise Context with @mentions", "time": "13 min", "type": "cursor",
             "core": "exercise-6/06-use-mentions.md",
             "objective": "Use @mentions to point the Agent at exact files, symbols, and context."},
    (2, 7): {"title": "Checkpoints", "time": "8 min", "type": "cursor",
             "core": "exercise-7/07-use-checkpoints.md",
             "objective": "Create and restore checkpoints before risky Agent experiments."},
    (2, 8): {"title": "Terminal Integration", "time": "13 min", "type": "cursor",
             "core": "exercise-8/08-run-terminal-command.md",
             "objective": "Let the Agent run terminal commands and react to command output."},
    (3, 1): {"title": "Ask Mode vs. Agent Mode", "time": "18 min", "type": "cursor",
             "core": "exercise-13/13-ask-mode-vs-agent-mode.md",
             "objective": "Learn when Ask Mode is read-only and when Agent Mode can edit files."},
    (3, 2): {"title": "Browser Tool", "time": "18 min", "type": "cursor",
             "core": "exercise-9/09-browser-tool-view-page.md",
             "objective": "Use the Browser tool so the Agent can inspect live web pages."},
    (3, 3): {"title": "Terminal Tool", "time": "20 min", "type": "cursor",
             "core": "exercise-11/11-terminal-tool-run-tests.md",
             "objective": "Use the Terminal tool to run tests, read output, and fix failures."},
    (3, 4): {"title": "Effective Prompting in Practice", "time": "22 min", "type": "cursor",
             "core": "exercise-26/26-effective-prompting-in-practice.md",
             "objective": "Write constrained prompts and reusable templates for real tasks."},
    (4, 1): {"title": "Creating a Rule", "time": "20 min", "type": "cursor",
             "core": "exercise-14/14-create-a-rule.md",
             "objective": "Create Cursor rules that persist coding standards for your team."},
    (4, 2): {"title": "Repository Instructions", "time": "13 min", "type": "cursor",
             "core": "exercise-15/15-use-agents-md.md",
             "objective": "Add repository instructions the Agent reads automatically."},
    (4, 3): {"title": "Creating and Invoking a Skill", "time": "20 min", "type": "cursor",
             "core": "exercise-16/16-create-a-skill.md",
             "core_extra": "exercise-17/17-invoke-a-skill.md",
             "objective": "Build and invoke reusable Agent skills for repeated workflows."},
    (5, 1): {"title": "Interactive CLI", "time": "20 min", "type": "cli",
             "core": "exercise-19/19-cli-interactive-mode.md",
             "objective": "Start an interactive Cursor CLI session from the terminal."},
    (5, 2): {"title": "One-Shot CLI", "time": "20 min", "type": "cli",
             "core": "exercise-20/20-cli-one-shot-mode.md",
             "objective": "Run single-shot Agent commands from scripts and CI."},
    (5, 3): {"title": "Cloud Handoff", "time": "18 min", "type": "cli",
             "core": "exercise-21/21-cli-cloud-handoff.md",
             "objective": "Hand off a local CLI task to a Cloud Agent with &."},
    (5, 4): {"title": "Listing and Resuming Sessions", "time": "20 min", "type": "cli",
             "core": "exercise-22/22-cli-list-resume-sessions.md",
             "objective": "List, name, resume, and compress CLI Agent sessions."},
    (6, 1): {"title": "Launching a Cloud Agent", "time": "25 min", "type": "cloud",
             "core": "exercise-23/23-cloud-agent-web-dashboard.md",
             "objective": "Launch a Cloud Agent from the Cursor UI and track its run."},
    (6, 2): {"title": "Cloud Agent Artifacts", "time": "25 min", "type": "cloud",
             "core": "exercise-25/25-cloud-agent-artifacts.md",
             "objective": "Collect and download artifacts produced by Cloud Agents."},
    (7, 2): {"title": "Generate and Test API Keys", "time": "15 min", "type": "api",
             "api": "exercise-1/01-generate-and-test-api-keys.md",
             "objective": "Create Admin and User API keys and verify authentication."},
    (7, 3): {"title": "Rate Limits and Error Handling", "time": "15 min", "type": "api",
             "api": "exercise-2/02-rate-limits-and-error-handling.md",
             "objective": "Handle 429 responses with backoff and rate-limit headers."},
    (7, 4): {"title": "ETag Caching", "time": "18 min", "type": "api",
             "api": "exercise-3/03-etag-caching.md",
             "objective": "Use ETags to avoid re-downloading unchanged API data."},
    (7, 5): {"title": "List Available Models", "time": "10 min", "type": "api",
             "api": "exercise-4/04-list-available-models.md",
             "objective": "Query available models and pick the right one programmatically."},
    (8, 1): {"title": "Create a Cloud Agent via API", "time": "15 min", "type": "api",
             "api": "exercise-5/05-create-cloud-agent.md",
             "objective": "Create a Cloud Agent run using curl or Python."},
    (8, 2): {"title": "Stream Agent Responses (SSE)", "time": "15 min", "type": "api",
             "api": "exercise-6/06-stream-agent-responses.md",
             "objective": "Stream Cloud Agent events with Server-Sent Events."},
    (8, 3): {"title": "List and Download Artifacts", "time": "15 min", "type": "api",
             "api": "exercise-7/07-list-and-download-artifacts.md",
             "objective": "Wait for completion, list artifacts, and download outputs."},
    (8, 4): {"title": "Webhooks and HMAC Verification", "time": "15 min", "type": "api",
             "api": "exercise-20/20-create-webhook-endpoint.md",
             "objective": "Receive webhooks and verify HMAC signatures."},
    (8, 5): {"title": "Test Webhooks with ngrok", "time": "15 min", "type": "api",
             "api": "exercise-21/21-test-webhooks-with-ngrok.md",
             "objective": "Expose a local server with ngrok and inspect webhook payloads."},
    (9, 1): {"title": "List Team Members", "time": "13 min", "type": "api",
             "api": "exercise-8/08-list-team-members.md",
             "objective": "List team members with pagination and export to CSV."},
    (9, 2): {"title": "Daily Usage Data", "time": "15 min", "type": "api",
             "api": "exercise-9/09-get-daily-usage-data.md",
             "objective": "Pull daily usage and build a weekly cost report."},
    (9, 3): {"title": "Set User Spend Limits", "time": "13 min", "type": "api",
             "api": "exercise-10/10-set-user-spend-limits.md",
             "objective": "Set and bulk-update per-user spending limits."},
    (9, 4): {"title": "Model Usage Analytics", "time": "13 min", "type": "api",
             "api": "exercise-12/12-get-model-usage-analytics.md",
             "objective": "Analyze model usage and identify optimization opportunities."},
    (9, 5): {"title": "Daily Active Users (DAU)", "time": "10 min", "type": "api",
             "api": "exercise-13/13-get-daily-active-users.md",
             "objective": "Report daily active users over a date range."},
    (9, 6): {"title": "Leaderboards", "time": "11 min", "type": "api",
             "api": "exercise-14/14-get-leaderboard.md",
             "objective": "Build leaderboards for tabs, AI lines, and agent runs."},
    (10, 1): {"title": "AI Commit Metrics", "time": "8 min", "type": "api",
              "api": "exercise-16/16-get-ai-commit-metrics.md",
              "objective": "Fetch AI commit metrics and calculate contribution percentage."},
    (10, 2): {"title": "Bulk Export via CSV Streaming", "time": "7 min", "type": "api",
              "api": "exercise-17/17-download-ai-commit-metrics-csv.md",
              "objective": "Stream large CSV exports for BI tools."},
    (10, 3): {"title": "Granular AI Change Events", "time": "7 min", "type": "api",
              "api": "exercise-18/18-get-granular-ai-change-metrics.md",
              "objective": "Query per-change AI events for compliance reporting."},
    (10, 4): {"title": "Reporting Dashboard Architecture", "time": "Take-home", "type": "api",
              "api": "exercise-23/23-build-complete-dashboard.md",
              "objective": "Design a leadership dashboard combining analytics APIs."},
}

